spring:
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://fin-mysql:3306/fintech?characterEncoding=UTF-8&serverTimezone=Asia/Seoul&useSSL=false
    username: fintech
    password: fintech
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  data:
    redis:
      host: fin-redis
      port: 6379
